export const GAME_CONFIG = {
  objectives: {
    noise: "nb_noise",
    alarms: "nb_alarms",
    locked: "nb_locked",
    perm: "nb_perm",
    startTick: "nb_start",
    patchReady: "nb_patch",
    fwall: "nb_fwall",
    ids: "nb_ids",
    enc: "nb_enc",
    victory: "nb_victory",
    knock: "nb_knock",
    p01: "nb_p01",
    p02: "nb_p02",
    p03: "nb_p03",
    p04: "nb_p04",
    p05: "nb_p05",
    p06: "nb_p06",
    p07: "nb_p07",
  },
  globalParticipant: "NB_GLOBAL",
  boundary: {
    minX: -867,
    maxX: 1253,
    minZ: -308,
    maxZ: 615,
    spawnX: 982,
    spawnY: 68,
    spawnZ: 396,
  },
  login: {
    username: "admin",
    password: "hexc0re2049",
  },
  portKnockSequence: ["1337", "22", "443"],
} as const;
